"""basic table week

Revision ID: 1c8c5c731744
Revises: 1d5343c3cf59
Create Date: 2020-01-05 11:20:29.744572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8c5c731744'
down_revision = '1d5343c3cf59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basics', sa.Column('week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basics', 'week')
    # ### end Alembic commands ###
