"""user table age

Revision ID: 32b300f4bd67
Revises: d3f701347442
Create Date: 2020-01-06 15:53:17.602392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b300f4bd67'
down_revision = 'd3f701347442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basics', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.drop_column('basics', 'score')
    # ### end Alembic commands ###
