"""height weight

Revision ID: 3a6b0230c98f
Revises: 32b300f4bd67
Create Date: 2020-01-18 22:42:07.926010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6b0230c98f'
down_revision = '32b300f4bd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basics', sa.Column('remark', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_basics_week'), 'basics', ['week'], unique=False)
    op.drop_column('basics', 'height')
    op.drop_column('basics', 'weight')
    op.add_column('users', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('job', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Float(precision=2), nullable=True))
    op.drop_column('users', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'weight')
    op.drop_column('users', 'job')
    op.drop_column('users', 'height')
    op.add_column('basics', sa.Column('weight', sa.FLOAT(), nullable=True))
    op.add_column('basics', sa.Column('height', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_basics_week'), table_name='basics')
    op.drop_column('basics', 'remark')
    # ### end Alembic commands ###
