"""basics change v0.2

Revision ID: 72167f92cde3
Revises: f201f397a85f
Create Date: 2020-04-01 22:42:34.134573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72167f92cde3'
down_revision = 'f201f397a85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basics', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basics', 'name')
    # ### end Alembic commands ###
