"""basics change v0.3

Revision ID: beb9db477c54
Revises: 72167f92cde3
Create Date: 2020-04-07 20:04:55.701228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb9db477c54'
down_revision = '72167f92cde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basics', sa.Column('long_run_score', sa.Integer(), nullable=True))
    op.add_column('basics', sa.Column('pull_up_score', sa.Integer(), nullable=True))
    op.add_column('basics', sa.Column('retrace_score', sa.Integer(), nullable=True))
    op.add_column('basics', sa.Column('sit_up_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basics', 'sit_up_score')
    op.drop_column('basics', 'retrace_score')
    op.drop_column('basics', 'pull_up_score')
    op.drop_column('basics', 'long_run_score')
    # ### end Alembic commands ###
